name: Build and deploy

on:
  push:
    branches: [ contextfree ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install and Build
        run: |
          yarn
          yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.WEBSITE_TOKEN }}
          BRANCH: gh-pages-contextfree
          FOLDER: packages/apps/build
